DROP TABLE hero_teams;
DROP TABLE teams;
DROP TABLE heroes;

CREATE TABLE heroes(
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  world VARCHAR(255),
  hireable BOOLEAN NOT NULL
);

CREATE TABLE teams(
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  region VARCHAR(255)
);

CREATE TABLE hero_teams(
  id SERIAL8 PRIMARY KEY,
  team_id SERIAL8 REFERENCES teams(id) ON DELETE CASCADE,
  hero_id SERIAL8 UNIQUE REFERENCES heroes(id) ON DELETE CASCADE
);
